dry-rb/dry-effects

lib/dry/effects/handler.rb
spec/unit/handler_spec.rb

Add handler mixin
Now we can introduce and eliminate effects with a nicer API
```ruby
class GetTimestamp
include Dry::Effects[:current_time]
def call
{ executed_at: current_time }
end
end
include Dry::Effects::Handler[:current_time, as: :with_time]
def call
op = GetTimestamp.new.freeze # op is immutable
with_time.(Time.now) { op.() } # one time value
with_time.(Time.now + 10) { op.() } # anothe time value
end
```
I'm thinking about replacing [] with () since it's unlikely we want to include many handlers at once. OTOH adding multiple effects makes sense so having [] may be reasonable for consistency.

Handler mixin

---

dry-effects.gemspec
lib/dry/effects.rb
lib/dry/effects/amb.rb
lib/dry/effects/cache.rb
lib/dry/effects/current_time.rb
lib/dry/effects/effect.rb
lib/dry/effects/errors.rb
lib/dry/effects/handler.rb
lib/dry/effects/initializer.rb
lib/dry/effects/interrupt.rb
lib/dry/effects/provider.rb
lib/dry/effects/providers/interrupt.rb
lib/dry/effects/providers/retry.rb
lib/dry/effects/providers/state.rb
lib/dry/effects/random.rb
lib/dry/effects/retry.rb
lib/dry/effects/stack.rb
lib/dry/effects/state.rb
spec/dry/effects_spec.rb
spec/intergration/random_spec.rb
spec/intergration/stacked_effects_spec.rb
spec/unit/stack_spec.rb

At the moment, every handler spawns a new fiber. Although it's the right way of doing things from the theoretical POV, we could use our own stack for effects that don't manipulate the control flow.

Reuse fibers when possible

---

dry-effects.gemspec
examples/amb.rb
examples/state.rb
lib/dry/effects.rb
lib/dry/effects/all.rb
lib/dry/effects/effects/retry.rb
spec/dry/effects_spec.rb
spec/intergration/amb_spec.rb
spec/intergration/cache_spec.rb
spec/intergration/current_time_spec.rb
spec/intergration/interrupt_spec.rb
spec/intergration/parallel_spec.rb
spec/intergration/random_spec.rb
spec/intergration/retry_spec.rb
spec/intergration/stacked_effects_spec.rb
spec/intergration/state_spec.rb
spec/unit/handler_spec.rb
spec/unit/stack_spec.rb

This replaces Dry::Effects.[]. The new API feels nicer. Will do the same for handlers in a separate PR

Generate methods for constructing effect modules

---

examples/amb.rb
examples/state.rb
lib/dry/effects/all.rb
lib/dry/effects/handler.rb
lib/dry/effects/provider.rb
lib/dry/effects/provider/class_interface.rb
spec/intergration/amb_spec.rb
spec/intergration/cache_spec.rb
spec/intergration/current_time_spec.rb
spec/intergration/interrupt_spec.rb
spec/intergration/parallel_spec.rb
spec/intergration/retry_spec.rb
spec/intergration/stacked_effects_spec.rb
spec/intergration/state_spec.rb
spec/unit/handler_spec.rb

To make it consistent with effect mixins:
Copy/paste from examples:
```ruby
class Operation
include Dry::Effects.State(:counter)
def call
3.times do
self.counter += 1
end
:done
end
end
class Wrapper
include Dry::Effects::Handler.State(:counter)
def initialize
@operation = Operation.new
end
def call
handle_state(0) { @operation.call }
end
end
Wrapper.new.call # => [3, :done]
```

Change API of handler mixins

---

lib/dry/effects/all.rb
lib/dry/effects/effects/defer.rb
lib/dry/effects/providers/defer.rb
spec/intergration/defer_spec.rb

It's a quite straightforward thing since it's backed by concurrent-ruby thread pools. Implementing fully featured async/await-like scheduler will be a lot more challenging task.
At this point, you're supposed to run handle_defer for spawning every fiber which is more or less equal to processing a single request. I'll be experimenting with enhancing the API.

Add defer effect

---

lib/dry/effects/all.rb
lib/dry/effects/effects/implicit.rb
lib/dry/effects/providers/implicit.rb
spec/intergration/implicit_spec.rb

Effect of implicitly passed function. Function lookup is done by searching a match using the class of the first argument but it can be changed in the future.
Setup:
```ruby
require 'dry/effects'
require 'dry/monads'
require 'dry/struct'
class Render
include Dry::Effects::Handler.Implicit(:show, lookup_map: {
Dry::Types::Monads::Maybe::Some => -> v, _default { v.value! },
Dry::Types::Monads::Maybe::None => -> _, default { default } 
})
def call
handle_show { yield }
end
end
class GreetUser
include Dry::Effects.Implicit(:show)
def call(user)
user_name = user.fmap(&:name)
<<~HTML
<div>Hello #{show(user_name, 'stranger')}</div>
HTML
end
end
```
Usage:
```ruby
render = Render.new
template = GreetUser.new
greet = -> user { render.() { template.(user) } }
User = Dry::Struct(name: 'string') …
```

Add implicit effect

---

lib/dry/effects/all.rb
lib/dry/effects/effects/env.rb
lib/dry/effects/handler.rb
lib/dry/effects/providers/env.rb
spec/intergration/env_spec.rb

Effect for reading environment values
```ruby
class Caller
include Dry::Effects::Handler.Env
def initialize
@callee = handle_env { Callee.new }
@callee = handle_env('DATABASE_URL' => '...') { Callee.new }
end
def call
@callee.()
end
end
class Callee
include Dry::Effects.Env(database_url: 'DATABASE_URL')
def initialize
@conn = Driver.new(database_url)
end
def call(...)
@conn.select(...)
end
end
```

Env effect

---

lib/dry/effects/all.rb
lib/dry/effects/effects/lock.rb
lib/dry/effects/providers/lock.rb
lib/dry/effects/providers/resolve.rb
spec/intergration/lock_spec.rb

Lock effect with replaceable backend. The API is not set yet but I'll give it a try soon. The idea is that provider will release all locks on exit, this makes lock management simple, you'll only need one top-level handler in the simplest case.

Lock effect

---

lib/dry/effects/effects/defer.rb
lib/dry/effects/providers/defer.rb
spec/intergration/defer_spec.rb

Blocks passed to `later` will be dispatched to executor upon provider exit

Add Defer#later

---

lib/dry/effects.rb
lib/dry/effects/effects/state.rb
lib/dry/effects/errors.rb
spec/intergration/state_spec.rb

This is a quite common case. It's not entirely pure, though, but who cares.

Call fallback block or return default value if state handler is missing

---

lib/dry/effects/effects/defer.rb
lib/dry/effects/providers/defer.rb
spec/intergration/defer_spec.rb
spec/support/capture_executor.rb
spec/support/null_executor.rb
spec/unit/providers/defer_spec.rb

It's arguable whether you want your application code to choose the executor. I need this because my code receives executor as an injected value but I'm thinking about refactoring to another approach in future. In any case, this option won't do a lot of harm.

Add executor option to defer effects

---

lib/dry/effects/effects/reader.rb
lib/dry/effects/effects/state.rb
spec/intergration/reader_spec.rb
spec/intergration/state_spec.rb

This option renames accessor methods.

Add `as` option for state and reader effects

---

Gemfile
dry-effects.gemspec
lib/dry/effects.rb
lib/dry/effects/constructors.rb
lib/dry/effects/effects/resolve.rb
lib/dry/effects/effects/state.rb
lib/dry/effects/errors.rb
lib/dry/effects/extensions.rb
lib/dry/effects/extensions/auto_inject.rb
lib/dry/effects/handler.rb
lib/dry/effects/providers/reader.rb
lib/dry/effects/providers/resolve.rb
lib/dry/effects/providers/state.rb
spec/extensions/auto_inject_spec.rb
spec/intergration/resolve_spec.rb
spec/intergration/stacked_effects_spec.rb
spec/intergration/state_spec.rb

Example usage, rough sketch but somewhat practical:
```ruby
Dry::Effects.load_extensions(:auto_inject)
class AppContainer
extend Dry::Container::Mixin
end
Import = Dry::Effects.AutoInject
...
class CreateUser
include Import['user_repo']
def call(params)
user_repo.create(params)
end
end
class ContainerMiddleware
include Dry::Effects::Handler.Resolve
def initialize(app)
@app = app
end
def call(env)
provide(AppContainer) { @app.(env) }
end
end
Import = Dry::Effects.AutoInject(dynamic: true)
RSpec.describe CreateUser do
include Dry::Effects::Handler.Resolve
subject(:create) { described_class.new }
let(:user_repo) { double(:user_repo) }
around { |ex| provide('user_repo' => user_repo, &ex) }
end
class ContainerMiddleware
def call(env)
provide(AppContainer, overridable: true) { @app.(env) }
end …
```

Add dry-auto_inject strategy for resolving dependencies with resolution effects

---

lib/dry/effects/effects/state.rb
lib/dry/effects/errors.rb
lib/dry/effects/providers/state.rb
spec/intergration/reader_spec.rb
spec/intergration/state_spec.rb

This allows postponing state initialization. I found it useful in certain circumstances. You won't be able to read undefined value (unless a default is given), though, so it's safe.

Support for not-defined state values

---

examples/state.rb
lib/dry/effects/provider/class_interface.rb
lib/dry/effects/providers/reader.rb
spec/intergration/async_spec.rb
spec/intergration/cache_spec.rb
spec/intergration/current_time_spec.rb
spec/intergration/defer_spec.rb
spec/intergration/env_spec.rb
spec/intergration/fork_spec.rb
spec/intergration/implicit_spec.rb
spec/intergration/lock_spec.rb
spec/intergration/parallel_spec.rb
spec/intergration/reader_spec.rb
spec/intergration/stacked_effects_spec.rb
spec/intergration/state_spec.rb

Generic:
`"handle_#{effect}"` -> `"with_#{effect}"`
State/reader:
`"handle_state"` -> `"with_#{scope}"` (like `"with_counter"`, `"with_user"`)
I figured these are the most sensible defaults

Rename default handler method

---

lib/dry/effects/errors.rb
lib/dry/effects/providers/reader.rb
lib/dry/effects/providers/state.rb
spec/intergration/reader_spec.rb
spec/intergration/state_spec.rb

Normally, you want state to be typed:
```ruby
class SetLanguage
include Dry::Effects::Handler.Reader(:lang, type: Symbol)
def call(env)
with_lang(detect_lang(env)) { @app.(env) }
end
end
```
```ruby
class Authenticate
include Dry::Effects::Handler.State(:current_user, type: Entities::User)
def call(env)
with_user do
self.user = authenticate(env)
@app.(env)
end
end
end
```

Add type check to state and reader providers

---

lib/dry/effects/providers/env.rb
lib/dry/effects/providers/resolve.rb
spec/intergration/env_spec.rb
spec/intergration/stacked_effects_spec.rb

The same way it works for resolve:
```ruby
context 'user-provided values' do
include Dry::Effects::Handler.Env
include Dry::Effects.Env(:foo)
it 'can be overridden by providing a handle option' do
handled = with_env(foo: 'external') do
with_env({ foo: 'internal' }, overridable: true) do
foo
end
end
expect(handled).to eql('external')
end
end
context 'ENV' do
include Dry::Effects.Env(env: 'RACK_ENV')
before { ENV['RACK_ENV'] = 'test' }
it 'can be overridden' do
handled = with_env('RACK_ENV' => 'production') do
with_env({}, overridable: true) do
env
end
end
expect(handled).to eql('production')
end
end
```

Make env handler overridable

---

lib/dry/effects/effects/cache.rb
spec/intergration/cache_spec.rb
spec/intergration/defer_spec.rb
spec/intergration/stacked_effects_spec.rb

It turned out the interface of `Cache` isn't really handy so I decided to change it:
```ruby
class Middleware
include Dry::Effects::Handler.Cache(:my_app)
def call(env)
with_cache { @app.(env) }
end
end
class PostRepo
include Dry::Effects.Cache(:my_app)
def for_user(user)
cache(:posts, user) { posts.by_user_id(user.user_id).to_a }
end
end
class PostRepo
prepend Dry::Effects.Cache(my_app: %i(for_user for_blog))
def for_user(user)
posts.by_user_id(user.user_id).to_a
end
def for_blog(blog)
posts.by_blog_id(blog.blog_id).to_a
end
end
```

Rework cache interface

---

lib/dry/effects/effects/fork.rb
lib/dry/effects/providers/fork.rb
spec/integration/fork_spec.rb

This gives more control over the stack and works better in practice. One should keep in mind that fork only copies stack values but does not re-instantiate stack calls for a bunch of reasons. 1. It's not possible in general (though we can always write providers in a compatible manner). 2. It's usually not needed, accessing these values is enough.
I think in future we'll have an (optional) warning or something like that for cases where stack cannot be safely copied. It depends on how often people need this in real life.

Pass current stack to as block argument instead of running it in place

---

Gemfile
lib/dry/effects/extensions.rb
lib/dry/effects/extensions/system.rb
spec/extensions/system/app/test/operations/create_user.rb
spec/extensions/system/app/test/repos/user_repo.rb
spec/extensions/system/system/app.rb
spec/extensions/system_spec.rb
spec/spec_helper.rb

This only does three things:
- uses effects to resolve dependencies. Presumably, this is only done in test and development environment. In production it shouldn't be required.
- boots all dependencies when finalized. We could have this as an option in dry-system instead.
- freezes and memoizes all dependencies. 100% FP.

Add experimental dry-system extension

---

lib/dry/effects/effects/lock.rb
lib/dry/effects/providers/lock.rb
spec/integration/lock_spec.rb

It can be useful to trace locks in order to provide more meaningful error messages etc. A backend can have a naive implementation and always return nil if it cannot be supported.

Support for metadata in the lock backend

---

lib/dry/effects/effects/current_time.rb
lib/dry/effects/providers/current_time.rb
spec/integration/current_time_spec.rb

Soon I will add support for time generator to make the testing story consistent

Support for time refresh in current_time

---

lib/dry/effects/providers/current_time.rb
spec/integration/current_time_spec.rb

It's similar to Resolve and makes using in tests even more flexible

Make current time provider overridable

---

lib/dry/effects/all.rb
lib/dry/effects/effects/current_time.rb
lib/dry/effects/effects/timestamp.rb
lib/dry/effects/providers/current_time.rb
lib/dry/effects/providers/current_time/time_generators.rb
lib/dry/effects/providers/timestamp.rb
spec/integration/current_time_spec.rb
spec/integration/timestamp_spec.rb
spec/spec_helper.rb

It's a twin of CurrentTime; the difference is in semantics. You want to use timestamps in places not affecting the business logic of your applications. It doesn't have `fixed: true` since it doesn't make a lot of sense for timestamps. Instead, you can set `step: 0` if needed.

Timestamp effect

---

lib/dry/effects/providers/interrupt.rb
spec/integration/interrupt_spec.rb
spec/integration/stacked_effects_spec.rb

Return whether there was an interruption. It's kind of logical you want to know if the inner block succeeded. It's always achievable with adding supplementary variables, but it looked as some cumbersome C-style to me. I stumbled upon this again when I tried to explain the effect in docs.

Change the Interrupt API

---

lib/dry/effects/all.rb
lib/dry/effects/effects/timeout.rb
lib/dry/effects/providers/timeout.rb
spec/integration/timeout_spec.rb

Another perfect example of using effects:
```ruby
class MakeRequest
include HTTParty
include Dry::Monads[:result, :try]
include Dry::Effects.Timeout(:http)
def call(url)
if timed_out?
Failure(:timeout)
else
Try[Net::ReadTimeout, Net::OpenTimeout, Net::WriteTimeout] {
self.class.get(url, timeout: timeout)
}.to_result.discard
end
end
end
request = MakeRequest.new
with_timeout = Object.new.extend(Dry::Effects::Handler.Timeout(:http, as: :call))
with_timeout.(1.0) { Array.new(5) { make_request.('http://httpstat.us/200?sleep=300') } }
```
It's already cool since it decouples time-to-process of your application from the intermediate code you have. But we can make even cooler by running it in parallel:
```ruby
with_parallel = Object.new.extend(Dry::Effects::Handler.Parallel(as: :call))
extend …
```

Add timeout effect

---

lib/dry/effects.rb
lib/dry/effects/all.rb
lib/dry/effects/frame.rb
lib/dry/effects/handler.rb
lib/dry/effects/provider/class_interface.rb
lib/dry/effects/providers/async.rb
lib/dry/effects/providers/current_time.rb
lib/dry/effects/providers/defer.rb
lib/dry/effects/providers/fork.rb
lib/dry/effects/providers/parallel.rb
spec/integration/random_spec.rb
spec/integration/stacked_effects_spec.rb
spec/spec_helper.rb
spec/support/effect_helper.rb
spec/unit/effects_spec.rb
spec/unit/handler_spec.rb
spec/unit/providers/current_time_spec.rb

It helps demonstrate effects:
```ruby
with_time = Dry::Effects[:current_time]
with_time.() { program_using_current_time }
```
I renamed existing `Dry::Effects::Handler` to `Dry::Effects::Frame`, it's really internal.

Handler constructors

---

docsite/source/effects/interrupt.html.md

Fix a typo in the Interrupt examples

---

lib/dry/effects/extensions.rb
lib/dry/effects/extensions/rspec.rb
spec/extensions/rspec_spec.rb

In particular, pending specs rely on Thread.current. I don't anticipate any problems with the patches since a) fortunately, RSpec doesn't use `Thread.current` a lot, b) patches are not invasive.

Add extension with RSpec patches to make some features work with dry-effects

---

docsite/source/effects/reader.html.md

@flash-gordon The `require` statement in the `Reader` documentation incorrectly refers to `dry-effects` instead of `dry/effects` like the other examples.

Fix incorrect require statement

---

docsite/source/effects/current_time.html.md

fix module name typo in current_type docs

---

docsite/source/effects/timeout.html.md

Based on [spec file](https://github.com/dry-rb/dry-effects/blob/master/spec/integration/timeout_spec.rb) this module should be used to add `with_timeout` method in `WithTimeout`

include missing Handler module in timeout docs

---

lib/dry/effects/all.rb
lib/dry/effects/effects/env.rb
lib/dry/effects/effects/implicit.rb
lib/dry/effects/effects/interrupt.rb
lib/dry/effects/effects/lock.rb
lib/dry/effects/effects/parallel.rb
lib/dry/effects/effects/random.rb

I'm pretty sure we'll switch to keywords-only eventually, it makes more sense for effects, they are like simple data structs.

Explicitly build effects with `.payload` and `.keywords`

---

spec/extensions/activesupport_taggedlogging_formatter.rb

`ActiveSupport::TaggedLogging` uses `Thread.current[]=` to track log tags.
This `Thread.current[]=` is however *Fiber* local variable (since Ruby
2.0)
Compare:
- https://ruby-doc.org/core-2.0.0/Thread.html#method-i-5B-5D
Attribute Reference—Returns the value of a fiber-local variable
(current thread's root fiber if not explicitely inside a Fiber),
using either a symbol or a string name. If the specified variable
does not exist, returns nil.
- https://tool.oschina.net/uploads/apidocs/ruby-1.9.3-core/Thread.html#method-i-5B-5D
Attribute Reference—Returns the value of a thread-local variable,
using either a symbol or a string name. If the specified variable
does not exist, returns nil.
The patch uses `#thread_variable_set` and `#thread_variable_get` which
are part of Ruby itself since 2.0. …

Extension to patch AS::TaggedLogging for compatibility

---

docsite/source/effects/current_time.html.md
docsite/source/index.html.md

Fix for an example with a typo: 
```
include Dry::Efefcts.Resolve(:subscription_repo)
```

Fix a small typo in a CurrentTime example

---

spec/integration/enumerator_spec.rb

I came across some incompatibility between dry-effects and built-in lazy enumerators. It's possible to make it work but it requires some coordination. Maybe I should add an API where stack is not copied but shared instead. It's a bit dirty but will work better/more efficient in this case.

Add an example of correct usage of lazy enumerators

---

Gemfile
lib/dry/effects/extensions/system.rb
spec/extensions/system/system/app.rb

This starts with a minor change to how we configure the auto_registrar for the container class in the `system` extension.
It also updates the custom `AutoRegistrar` implementation to match the [new behaviour released in 0.19.0](https://github.com/dry-rb/dry-system/compare/v0.18.1...v0.19.0#diff-fc89812a49544a3a1113c3308b12512ee9073599a471c5ed1d0f3aa20a3a4341).

Upgrade to use latest dry-configurable and dry-system

---

docsite/source/index.html.md

I've published a tutorial, including video guide of using dry-effects in Hanami applications. It covers basic examples of usage, but also explains the benefits. I think it is useful to contain it on this list.

Add external resource of dry-effects tutorial

---

docsite/source/effects/resolve.html.md

```ruby
1) CreateUser creates a user
Failure/Error: user_repo.create(values.merge(name: name))
#<Double :user_repo> received :create with unexpected arguments
expected: ({:first_name=>"John", :last_name=>"Doe", :name=>"John Doe"}) (keyword arguments)
got: ({:first_name=>"John", :last_name=>"Doe", :name=>"John Doe"}) (options hash)
```

fixes typo in Resolve example
